#默认使用配置
#spring:
#  profiles:
#    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.skyfaith.domain
  mapper-locations: classpath:mapper/*.xml


#开发配置
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:sqlite:C:/db/emslabel.db
    driver-class-name: org.sqlite.JDBC
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource