#默认使用配置
#spring:
#  profiles:
#    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.skyfaith.domain
  mapper-locations: classpath:mapper/*.xml


#开发配置
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=EMSLabel
    username: ems
    password: ems*64586103
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource